name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Lấy code từ repository
    - name: Checkout code
      uses: actions/checkout@v3.2.0

    # Cài Node.js (phiên bản 18)
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Chạy MongoDB và RabbitMQ bằng Docker (liên kết Docker)
    - name: Setup MongoDB & RabbitMQ
      uses: isbang/compose-action@v1
      with:
        compose-file: ./docker-compose.yml

    # Tạo file .env cho Auth & Product
    - name: Create .env file
      run: |
        echo "MONGODB_AUTH_URI=mongodb://mongodb:27017/auth_db" >> auth/.env
        echo "JWT_SECRET=mysecretkey" >> auth/.env
        echo "JWT_SECRET=mysecretkey" >> product/.env
        echo "MONGODB_PRODUCT_URI=mongodb://mongodb:27017/product_db" >> product/.env
        echo "LOGIN_TEST_USER=user1" >> product/.env
        echo "LOGIN_TEST_PASSWORD=12345" >> product/.env

    # Cài dependencies cho từng service
    - name: Install dependencies
      run: |
        cd auth && npm ci && cd ..
        cd product && npm ci && cd ..
        npm ci

    # Chạy test cho Auth
    - name: Run tests for auth
      run: |
        cd auth
        npm test

    # Chạy test cho Product (Auth chạy nền)
    - name: Run tests for product
      run: |
        cd auth && npm start &
        sleep 5
        cd ../product
        npm test
